### ISSUE TITLE
CCL 설정 페이지 필요

### ISSUE THREAD

**Issue by gaon12** [librewiki/liberty-engine#101]
다른 위키 엔진들은 페이지 하단부에 CCL을 표시하고 있습니다. 그러나 리버티 엔진은 CCL을 설정 할 수 있는 곳이 없습니다.

관리자 페이지에서 CCL(드물지만 다른 라이선스)을 설정 할 수 있는 페이지가 필요합니다.

+ [예전 issue](https://github.com/librewiki/liberty-engine/issues/48)에도 올라와 있지만, 정식적인 서비스를 위해서는 빠르게 도입되야 할 것 같습니다.

**Comment by NessunKim** [comment]
22cdd4ea83c9c91737ec8f3069855a4e68e35083
관리자 페이지에 추가했습니다.
