### ISSUE TITLE
유튜브, 카카오tv 영상 안나옴

### ISSUE THREAD

**Issue by gaon12** [librewiki/liberty-engine#102]
저번에 [이슈](https://github.com/librewiki/liberty-engine/issues/99)로 남겼는데 패치하셨다고 해서 확인을 해봤더니 잘림 현상은 수정되었지만 여전히 영상은 나오지 않고 있습니다.

**Comment by NessunKim** [comment]
프론트엔드 업데이트가 제대로 안 된 것 같습니다. npm run upgrade를 다시 한 번 실행해보시고 알려주세요.

**Comment by gaon12** [comment]
그래도 여전히 같은 메시지가 뜨면서 안나오네요

**Comment by gaon12** [comment]
View 폴더 git pull을 하지 않아서 그러네요.;;
정상적으로 작동합니다.
