### ISSUE TITLE
각주 표시 안됨

### ISSUE THREAD

**Issue by gaon12** [librewiki/liberty-engine#103]
`<ref>각주</ref>` 이런식으로 각주를 만들면, [1] 과 같이 각주 번호는 뜨지만, 클릭시 반응이 없습니다.(모바일에서만)

또한 하단 각주 내용도 뜨지 않습니다.(모바일, PC 둘다 안뜸)

[여기](https://beta.gaonwiki.com/article/%EB%A6%AC%EB%B2%84%ED%8B%B0%20%EC%97%94%EC%A7%84%20%EA%B0%9C%EC%84%A0%EC%82%AC%ED%95%AD)서 확인해 보실 수 있습니다.

**Comment by NessunKim** [comment]
원하는 위치에 <references />가 있어야 각주가 나옵니다.

**Comment by gaon12** [comment]
`<references />` 코드가 없으면 기본적으로 최하단에 뜨도록 해야 할 것 같습니다. 일일이 코드를 넣는것은 비효율적인 것 같습니다.

+ 모바일 각주 표시는 아직 패치 안됐나요?

**Comment by NessunKim** [comment]
6d85f4e
