### ISSUE TITLE
없는 문서들 검색시 오류 발생

### ISSUE THREAD

**Issue by gaon12** [librewiki/liberty-engine#105]
위키에 없는 문서를 검색시 500 에러가 발생합니다.
`Request failed with status code 500`

URL에서 직접 입력하면 생성이 가능하지만, 검색창에서 검색하면 오류가 발생합니다.

오류 로그는 요청시 메일로 보내드리겠습니다.(ip 주소가 포함되어 있어서 깃허브에 못올리는 점 양해 부탁드립니다.)

**Comment by NessunKim** [comment]
```bash
sudo mysql
mysql> INSTALL SONAME 'ha_mroonga';
```

이걸로 해결이 되는지 한번 확인해주세요.

**Comment by gaon12** [comment]
> ```bash
> sudo mysql
> mysql> INSTALL SONAME 'ha_mroonga';
> ```
> 
> 이걸로 해결이 되는지 한번 확인해주세요.


여전히 같은 오류 메시지가 뜨네요 ㅠㅠ

**Comment by gaon12** [comment]
재설치로 해결했습니다
