### ISSUE TITLE
넘겨주기 문제

### ISSUE THREAD

**Issue by Lamelime** [librewiki/liberty-engine#24]
https://github.com/librewiki/liberty-engine/issues/19
https://github.com/librewiki/liberty-engine/issues/21

위 두 이슈처럼 넘겨주기 및 삭제 목록이 보여야 됩니다.

현재는 넘겨주기 및 넘겨주기 삭제를 하면 Sidebar 에서만 어떤 문서를 편집했는지 나옵니다. (뭔 짓을 했는지는 나오지 않음)

아님 악용되어 이렇게 됩니다. (누가 했지)
https://liberty.nessun.ga/redirections/%EB%8C%80%EB%AC%B8

**Comment by 2DU** [comment]
제가 했는데요

**Comment by Lamelime** [comment]
모르고 들어갔다가 브라우저 터졌어요

**Comment by 2DU** [comment]
저런

**Comment by NessunKim** [comment]
duplicated #19
