### ISSUE TITLE
엔진 설치에 오류가 있습니다.

### ISSUE THREAD

**Issue by HwaShinC** [librewiki/liberty-engine#39]
![default](https://user-images.githubusercontent.com/22009744/38170855-9eaa3ef8-35c9-11e8-8bc9-8cfd5a523e9c.png)

전에는 분명 설치 과정대로 해서 위키가 제대로 열렸는데 지금은 nginx 초기 화면만 계속 뜹니다.
가상 서버에서 설치 한번 테스트해주시고 오류가 있는지 확인 부탁드립니다.

**Comment by NessunKim** [comment]
테스트해보니 설치는 잘 되는데 혹시 로그를 위쪽까지 업로드해주실 수 있나요?

**Comment by HwaShinC** [comment]
[log.txt](https://github.com/librewiki/liberty-engine/files/1868680/log.txt)
npm run setup 을 할때 오류가 나는것 같습니다.

**Comment by NessunKim** [comment]
루트에 비밀번호가 걸려 있으면 현재 스크립트가 잘 작동하지 않습니다. 테스트 후 수정하겠습니다.

**Comment by HwaShinC** [comment]
음... 우분투 버전이 문제였던것 같습니다 ㅜ.ㅜ

저 스크린샷은 ubuntu-14.04 버전이고, ubuntu-16.04으로 다시 설치해보니 오류 하나도 없이 잘 구동됩니다. 

불편을 끼쳐드려 죄송합니다.

**Comment by Lastorder-DC** [comment]
@HwaShinC 재설치하며 루트 비밀번호가 초기화되어 동작한것으로 우분투 버전과 무관합니다.

**Comment by HwaShinC** [comment]
@Lastorder-DC 음 그러고보니 14버전은 db 루트 비밀번호를 설정하라는게 뜨고, 16버전은 안뜨던데... 아무튼 지금은 잘되네요. 감사합니다.
