### ISSUE TITLE
넘겨주기의 문서화

### ISSUE THREAD

**Issue by pseol2190** [librewiki/liberty-engine#45]
다른 엔진처럼 넘겨주기를 문서화하는 것이 나을 듯 합니다. 물론 현재 문서에서 넘겨주기를 만들 수 있는 메뉴는 유지하고, 해당 메뉴에서 넘겨주기를 만들 경우 자동으로 해당 문서명으로 `#redirect [[문서명]]`이 포함된 문서가 생성되도록 하는 것이 더 좋을 듯 합니다.
현재 방식으로는 넘겨주기와 문서의 충돌 가능성도 큽니다.

**Comment by Katinor** [comment]
어떤 시나리오가 발생하는지 예시를 들어주시겠습니까?

이미 존재하는 넘겨주기 또는 문서를 넘겨주기 이름으로 추가하는 것은 엔진에서 거부하고 있어 충돌이 발생한다고는 보기 힘듭니다.

해당하는 행위를 했을 경우에는 다음과 같은 경고문이 표시되고, 진행되지 않습니다.

> 해당 이름을 가진 문서나 넘겨주기가 이미 존재합니다.
