### ISSUE TITLE
Add manual for Windows

### ISSUE THREAD

**Issue by ghost** [librewiki/liberty-engine#50]
Please add manual in README.md about how to install LibertyEngine on Windows.

**Comment by Katinor** [comment]
@pseol2190 @passpazs 답변 어케할거임

**Comment by Katinor** [comment]
애초에 이거 sudo써서 설치해야해서 윈도우에 안굴러갈건데...

**Comment by NessunKim** [comment]
@pseol2190 윈도우에서 깔아보고 답변해드리겠습니다.

**Comment by Lastorder-DC** [comment]
설치 과정중  sudo가 있으나 윈도우에서는 관리자 권한이 불필요하기에 문제가 되진 않습니다.

역으로 APM을 사용자가 직접 설치해야 하는 특성상 모든 케이스에 대응하는것이 불가능한데, APM을 설치할 정도 실력이면 설정파일 수정정도는 직접 할수있으리라 봅니다.

**Comment by Hoto-Cocoa** [comment]
sudo가 커맨드에 들어가면 커맨드 없다고 떠서 진행이 안되죠...

**Comment by Lastorder-DC** [comment]
@Hoto-Cocoa 
https://github.com/librewiki/liberty-engine/blob/master/bin/install#L37-L56
https://github.com/librewiki/liberty-engine/blob/master/bin/install#L231-L235

sudo가 들어가는 명령은 모두 건너뛸수 있습니다.

**Comment by NessunKim** [comment]
스크립트 만들면 되니까 기다려보세요

**Comment by NessunKim** [comment]
아니면 PR주셔도 되고
