### ISSUE TITLE
첫 설치 후 실행시 pm2 ecosystem.config.js파일이 없어서 실행이 안됩니다

### ISSUE THREAD

**Issue by leedoe** [librewiki/liberty-engine#55]
AWS 우분투 18버전에서 처음 설치후 테스트해보려 하는데

npm start, npm run dev

둘다 pm2에서 문제가 생겨서 실행이 되질 않습니다

ecosystem.config.js파일을 직접 만들어주면 될까요

**Comment by NessunKim** [comment]
npm run setup 실행하셨나요?

**Comment by leedoe** [comment]
아 setup을 안했네요. 감사합니다
