### ISSUE TITLE
유튜브, 카카오tv 영상 표시 오류

### ISSUE THREAD

**Issue by gaon12** [librewiki/liberty-engine#99]
1. 크롬 계열 브라우저들로 접속시 유튜브와 카카오tv 모두 영상이 나오지 않습니다.

서버에 대한 요청이 확장앱에 의해 차단되었습니다. 라는 메시지만 뜹니다.
익스플로러에서는 정상적으로 뜹니다.

[위키 테스트 문서](https://beta.gaonwiki.com/article/%ED%85%8C%EC%8A%A4%ED%8A%B8%2F%EC%98%81%EC%83%81)

2. 윗부분에 유튜브든 카카오tv든 영상이 삽입되어 있으면, 영상 아랫부분은 어떤 내용을 넣더라도 잘려서 안보입니다. 물론 편집 페이지에서는 정상적으로 적혀져 있습니다. (익스플로러도 문제 발생)

**Comment by aris-mhkim** [comment]
제보 감사드립니다.

1. Content Security Policy 관련해 문제가 있었습니다.
2. Cheerio 라이브러리 관련 문제가 있어, 임시로 수정하였습니다.

git pull 이후 npm run upgrade 해보시길 바랍니다.

**Comment by NessunKim** [comment]
이슈 제보 감사합니다.
1. Content Security Policy 관련 문제가 있었습니다.
2. Cheerio가 내용이 빈 iframe을 self-closing 태그로 만드는 버그가 있어 발생한 문제입니다. 임시로 해결했습니다.

git pull이후 npm run upgrade 해보시길 바랍니다.

**Comment by gaon12** [comment]
영상 하단부 잘림 현상은 해결되었지만, 여전히 영상이 나오지 않고 있습니다.

나오는 메시지는 동일하네요.
